services:
  postgres:
    image: postgres:latest
    container_name: account_manager_postgres
    env_file:
      - .env
    volumes:
      - account_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432/tcp

volumes:
  account_data: